# ワークフロー名
name: test_keybot

# 発火タイミング
on:
# push:
  schedule:
    - cron: '5 10 * * 0'
    - cron: '5 13 * * MON-FRI'
    - cron: '5 10 * * 6'

jobs:
  build:
    # MacOS BigSurの最新版環境内で処理
    runs-on: ubuntu-latest
    
    # 実行する処理＆コマンド指定
    steps:
     - uses: actions/checkout@v2
     - name: Set up Python 3.9
       uses: actions/setup-python@v1
       with:
        python-version: 3.9
     - name: Install dependencies
       run: |
         # pip更新
         python -m pip install --upgrade pip
         # 必要なパッケージインストール
         pip install line-bot-sdk
     - name: Run script
       env: 
        CHANNEL_ACCESS_TOKEN: "YOUR_CHANNEL_ACCESS_TOKEN"
        USER_ID: "YOUR_USER_ID"
       run: |
        # main.py実行
        python main_01.py
